# Generated by Django 2.2.1 on 2019-09-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advance_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='std_name',
        ),
    ]
